#!/usr/bin/env python
'''
Usage: dxttool <options> filename

    -c, --compress          Compress an image to DXT
    -d, --decompress        Decompress an image from DXT to PNG
    -o, --output filename   Change the output filename
    -h, --help              Show this usage

Compress an image:
    dxttool -c <filename.png>

Decompress an image:
    dxttool -d <filename.dxt>

Note: Decompression will always output an png image
Note: Compression accept PNG, JPEG, GIF, TGA...
'''

import sys
from sys import exit, argv, stdout
import getopt
import pygame
import squish
import struct

def usage():
    print __doc__

def trace(msg):
    stdout.write(msg)
    stdout.flush()

def _nearest_pow2(v):
    # From http://graphics.stanford.edu/~seander/bithacks.html#RoundUpPowerOf2
    # Credit: Sean Anderson
    v -= 1
    v |= v >> 1
    v |= v >> 2
    v |= v >> 4
    v |= v >> 8
    v |= v >> 16
    return v + 1

if __name__ == '__main__':

    try:
        opts, args = getopt.getopt(argv[1:], 'hcdo:',
                ['help', 'compress', 'decompress', 'output='])
    except getopt.GetoptError, err:
        print str(err)
        usage()
        exit(1)

    sys.argv = sys.argv[:1]

    command = None
    output = None
    for o, a in opts:
        if o in ('-c', '--compress'):
            command = 'compress'
        elif o in ('-d', '--decompress'):
            command = 'decompress'
        elif o in ('-h', '--help'):
            usage()
            exit(0)
        elif o in ('-o', '--output'):
            output = a
        else:
            assert False, 'unhandled option'


    if command is None:
        usage()
        exit(1)

    if len(args) != 1:
        usage()
        exit(1)

    fn = args[0]

    pygame.display.init()

    if command == 'compress':

        from kivy.lib.ddsfile import DDSFile

        if output is None:
            output = fn.rsplit('.', 1)[0] + '.dds'

        img = pygame.image.load(fn)
        print 'Original image is', img.get_size()
        img = img.subsurface(img.get_bounding_rect())
        width, height = img.get_size()
        print 'Bounding box found is', img.get_size()

        # ensure RGBA
        if img.get_bytesize() != 4:
            img = img.convert(32)

        # create container
        dds = DDSFile()

        # first image, ensure width/height are pot
        #
        iwidth = _nearest_pow2(width)
        iheight = _nearest_pow2(height)
        iwidth = iheight = max(iwidth, iheight)
        if iwidth != width or iheight != height:
            print 'Upgrade from', (width, height), 'to', (iwidth, iheight)
            surf = pygame.Surface((iwidth, iheight), depth=32)
            cx = iwidth / 2 - width / 2
            cy = iheight / 2 - height / 2
            surf.blit(img, (cx, cy))
            img = surf
            width = iwidth
            height = iheight

        # convert
        trace('Converting %s' % fn)
        level = 0
        minsize = 1024
        while True:
            assert(img.get_bytesize() == 4)

            if width <= minsize and height <= minsize:
                trace(' %d(%d,%d)' % (level, width, height))
                data = pygame.image.tostring(img, 'RGBA', True)
                data = squish.compressImage(data, width, height,
                        squish.DXT1 | squish.COLOR_ITERATIVE_CLUSTER_FIT |
                        squish.WEIGHT_COLOR_BY_ALPHA)
                dds.add_image(level, 32, 'dxt1', width, height, data)
            else:
                level = -1

            if width == 1 or height == 1:
                break

            # next iteration
            width = width // 2
            height = height // 2
            level += 1

            # reduce image
            img = pygame.transform.smoothscale(img, (width, height))
            assert(img.get_size() == (width, height))

        dds.save(output)
        trace('Done !\n')

    else:

        assert('Unimplemented')
        # Everything need to be redone

        with open(fn, 'rb') as fd:
            data = fd.read()

        size = struct.calcsize('cccIII')
        header, data = data[:size], data[size:]
        if len(header) != size:
            print 'Corrupted file, header too small'
            exit(1)

        if not header.startswith('DXTx'):
            print 'Corrupted file, invalid magic header'
            exit(1)

        print len(header), struct.calcsize('ccccIII')
        width, height, flags = struct.unpack('III', header[4:])


        # convert
        img_raw = squish.decompressImage(data, width, height, flags)

        # write
        if output is None:
            output = fn.rsplit('.', 1)[0] + '.png'
        img = pygame.image.fromstring(img_raw, (width, height), 'RGBA')
        pygame.image.save(img, output)

        print 'Written to', output

